<?php
$winner = 'n';
$box = array('','','','','','','','','');
if (isset($_POST['submitbtn'])) {
 
$hasBlank = false;
foreach (range(0, 8) as $i) {
  $val = array_key_exists('box' . $i, $_POST) 
       ? $_POST['box' . $i]
       : '';
  if (empty($val) && $hasBlank === false) $hasBlank = true;
  $box[] = $val;
}
 
function check($box, $x) {
  // [ 0, 1, 2 ]
  // [ 3, 4, 5 ]
  // [ 6, 7, 8 ]
 
         // horizontal
  return ($box[0] == $x && $box[1] == $x && $box[2] == $x)
      || ($box[3] == $x && $box[4] == $x && $box[5] == $x) 
      || ($box[6] == $x && $box[7] == $x && $box[8] == $x)
         // vertical 
      || ($box[0] == $x && $box[3] == $x && $box[6] == $x) 
      || ($box[1] == $x && $box[4] == $x && $box[7] == $x) 
      || ($box[2] == $x && $box[5] == $x && $box[8] == $x)
         // diagonal 
      || ($box[0] == $x && $box[4] == $x && $box[8] == $x) 
      || ($box[2] == $x && $box[4] == $x && $box[6] == $x);
}
 
function doComputerTurn(&$box, $x) {
  $empties = array_keys($box, '');
  if (!$empties) return;
  $key = array_rand($empties);
  $box[$empties[$key]] = $x;
}
 
if ($hasBlank) {
  echo 'keep playing!';
} elseif (check($box, 'o') && check($box, 'x')) {
  echo 'draw!';
} elseif (check($box, 'x')) {
  echo 'x wins!';
} elseif (check($box, 'o')) {
  echo 'o wins!';
}
 

}
?>
<html>
<head>
<title>game</title>
<style type="text/css">
#box{
		background-color :#99FFCC;
		border: 1px solid #008000;
		width: 100px;
		height: 100px;
		font-size: 66px;
		text-align: center;
		
}
#go {
width:200px;
font-family: 'Comic Sans MS';
font-size: 40px;
}
</style>
</head>
<body bgcolor="pink">
<body><CENTER>
<H1>TIC-TAC-TOE</H1>
<P> PLACE AN X IN A SQUARE, THEN CLICK FIRE FOR THE COMPUTER TO TAKE A TURN</P>
<form name="tictactoe" method="post" action="game.php">
<?php
for ($i=0; $i<=8; $i++) {
	printf('<input type="text" name="box%s" value ="%s" id = "box">', $i, $box[$i]);
	if ($i == 2 || $i == 5 || $i == 8 ) {
	print('<br>');
	}
} // end for loop
if ($winner == 'n') {
print('<input type="submit" name="submitbtn" value="fire" id="go">');
} else {
	print('<input type="button" name="newgamebtn" value= "New Game" 
onclick ="window.location.href=\'game.php\'">');
}

</form>
</body>
</html>
 



