/**
 * @file
 * creates a custom block
 * Implementation of hook_menu().
 */
 
/**
 * Implementation of dandeblock_block_info().
 */
function dandeblock_block_info() {
  $blocks['my-block-id'] = array(
    'info' => t('Block Name'),
  );
  return $blocks;
}
 
/**
 * Implementation of dandeblock_block_view().
 */
function dandeblock_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'my-block-id':
      $block['subject'] = t('Block Name');
      $block['content'] = dandeblock_contents();
      break;
  }
  return $block;
}
 
/**
 * custom html block
 * @return string
 */
function dandeblock_contents() {
  return '
    </p><div class="body">
      Hello World, this is a example custom Block
    </div><p>
  ';
}